version: "3.2"

services:

  analyzer:
    image: scottypate/equatorial:latest
    container_name: equatorial
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: "\"run 50000 10000\""
    environment:
      - JAVA_OPTS="-Xms6g -Xmx15g"
    volumes:
      - type: bind
        source: ./src/main/scala
        target: /equatorial/src/main/scala
