version: "3"

services:

  analyzer:
    image: scottypate/equatorial:latest
    container_name: equatorial
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: "\"run 1000000 10000\""
    volumes:
      - type: bind
        source: ./src/main/scala
        target: /equatorial/src/main/scala