defaults: &defaults
    working_directory: ~/equatorial
    docker:
        - image: circleci/openjdk:8-jdk

version: 2
jobs:
  build:
    <<: *defaults
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cat /dev/null | sbt compile
      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      # run tests!
      #- run: cat /dev/null | sbt test:test

  deployProduction:
    <<: *defaults
    steps:
        - checkout
        - setup_remote_docker
        - restore_cache:
            key: deps1-{{ .Branch }}-{{ checksum "build.sbt" }}
        - run:
            command: |
                docker build -t scottypate/equatorial .
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                docker push scottypate/equatorial:latest

workflows:
    version: 2
    build_workflow:
        jobs:
            - build
            - deployProduction:
                requires:
                    - build
                filters:
                    branches:
                        only:
                            /master/